from .base import DESCRIPTION_JIPIPE

NODE_SEARCH_GENERATE_QUERY=f"""{DESCRIPTION_JIPIPE}
You will be given a JIPipe node with its description. The description explains the function of the node.
You are responsible for generating a dataset which represents search requests for JIPipe nodes. The dataset is made up of query/answer pairs and you are responsible for generating a fitting search query.
The query should adhere to the following criteria:
- The query should reflect the scenario of a user/researcher searching for a JIPipe node, which solves a certain task.
- The query should not include the name of the node.
- The query is posed in such a way that the researcher does not know the name of the node, but rather wants to identify it by very shortly stating its desired functionality.
- The query should be short.
- Only include the query in your answer.

Generate a search query that meets the criteria about the following node. Base the search query on the description of the node. Is no description given, base the search query on the name of the node.

Name: {{node_name}}
Description: {{node_description}}


Check also that your search query is unique to the already created search queries.
already generated search queries:
{{queries}}
"""

NODE_SEARCH_JUDGE_PROMPT=f"""{DESCRIPTION_JIPIPE}
You are a quality evaluator. You will be given a JIPipe node in json format including the node name with a short description and a search query. 
The search query was generated by another model representing a real-life scenario in which a JIPipe user searches for this given node.
You must assess, if the query meets these criteria:
- The query should reflect the scenario of a user/researcher searching for a JIPipe node, which solves a certain task.
- The query should not include the name of the node.
- The query is posed in such a way that the researcher does not know the name of the node, but rather wants to identify it by very shortly stating its desired functionality.
- The query should be short.
- The answer to the query is the name of the given node.

Answer "yes", if the question meets all quality criteria, "no" otherwise. Only include either "yes" or "no" in your answer. Only answer "yes" if you are absolutely sure.

Query: {{query}}
Node: {{node_definition}}"""